services:
  postgres:
    image: postgres:18
    container_name: subscriptions_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  app:
    build: .
    container_name: subscription_app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
      - .env  

volumes:
  postgres_data:
